# Generated by Django 3.2.20 on 2023-12-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happy_Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='В цифрах!', verbose_name='Количество успехов')),
                ('title', models.CharField(help_text='Успешные Проекты', max_length=255, verbose_name='Название успеха')),
            ],
            options={
                'verbose_name': 'Успех',
                'verbose_name_plural': 'Успехи',
            },
        ),
    ]
