# Generated by Django 3.2.20 on 2023-12-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_happy_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SlugField(verbose_name='URL')),
                ('image', models.ImageField(upload_to='portfolio/', verbose_name='Фото портфолио')),
            ],
        ),
    ]
