# Generated by Django 3.2.20 on 2023-12-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(default=2, max_length=255, verbose_name='Название портфолио'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('branding', 'Брендинг'), ('design', 'Дизайн'), ('wordpress', 'WordPress'), ('marketing', 'Маркетинг')], help_text='Выберите категорию', max_length=255),
        ),
    ]
