# Generated by Django 3.2.20 on 2023-12-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20231205_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email: '),
        ),
        migrations.AddField(
            model_name='settings',
            name='phone',
            field=models.CharField(blank=True, max_length=13, verbose_name='Телефон: '),
        ),
    ]
